
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Sep 23 09:33:20 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BINAIRE = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

