
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOM = 8;
  public static final int TOTAL = 6;
  public static final int NOMARTICLE = 9;
  public static final int EOF = 0;
  public static final int POINT = 4;
  public static final int ENTIER = 2;
  public static final int error = 1;
  public static final int DEUXPOINT = 7;
  public static final int VIRG = 3;
  public static final int FACTURE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTIER",
  "VIRG",
  "POINT",
  "FACTURE",
  "TOTAL",
  "DEUXPOINT",
  "NOM",
  "NOMARTICLE"
  };
}

