
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Sep 28 13:55:27 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOM = 8;
  public static final int TOTAL = 6;
  public static final int NOMARTICLE = 9;
  public static final int EOF = 0;
  public static final int POINT = 4;
  public static final int ENTIER = 2;
  public static final int error = 1;
  public static final int DEUXPOINT = 7;
  public static final int VIRG = 3;
  public static final int FACTURE = 5;
}

