
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Sep 23 08:33:03 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int ENTIER = 2;
  public static final int EOF = 0;
}

