
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POINTVIRG = 18;
  public static final int CHAINE = 3;
  public static final int DEUXPOINT = 11;
  public static final int ACTIVITES = 6;
  public static final int ASPECTLIEU = 2;
  public static final int POINT = 12;
  public static final int ANIMATEUR = 7;
  public static final int EGALE = 14;
  public static final int HORAIRE = 4;
  public static final int EOF = 0;
  public static final int VIRG = 13;
  public static final int PARTICIPANTS = 8;
  public static final int CENTRE = 10;
  public static final int error = 1;
  public static final int ACCFMT = 17;
  public static final int ACCOVT = 16;
  public static final int JOUR = 5;
  public static final int FIN = 9;
  public static final int PRENOM = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASPECTLIEU",
  "CHAINE",
  "HORAIRE",
  "JOUR",
  "ACTIVITES",
  "ANIMATEUR",
  "PARTICIPANTS",
  "FIN",
  "CENTRE",
  "DEUXPOINT",
  "POINT",
  "VIRG",
  "EGALE",
  "PRENOM",
  "ACCOVT",
  "ACCFMT",
  "POINTVIRG"
  };
}

