
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Sep 28 15:31:09 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAROVT = 2;
  public static final int error = 1;
  public static final int PARFMT = 3;
  public static final int EOF = 0;
}

